# Description:
#             This is a simple Makefile to compile PUMA in C
# Authors:
#             Marieke Kuijjer, Marouen Ben Guebila 10/2019

PUMA: PUMA.c
	gcc -coverage -O3 -o PUMA PUMA.c -lm
	
clean:
	rm *.o *.gcno *.gcda *.pairs
