# Description:
#             This is a simple Makefile to compile PANDA in C
# Authors:
#             Kimberley Glass, Marouen Ben Guebila 05/2019

PANDA: PANDA_v2.c
	gcc -coverage -O3 -o PANDA PANDA_v2.c -lm
	
clean:
	rm *.o *.gcno *.gcda *.pairs
